// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/entry.dart';
import 'api/error.dart';
import 'api/feed.dart';
import 'api/opml.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAppInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1620617620;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_rss_reader',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiAppAppVersion();

  Future<ArticleViewMode> crateApiTypesArticleViewModeDefault();

  Future<void> crateApiEntryDeleteCategory({required String categoryId});

  Future<void> crateApiFeedDeleteFeed({required String feedId});

  Future<List<FeedCandidate>> crateApiFeedDiscoverFeeds({required String url});

  Future<String> crateApiOpmlExportOpml();

  Future<AdjacentEntries> crateApiEntryGetAdjacentEntries({
    required String entryId,
    String? feedId,
    required bool unreadOnly,
    required bool starredOnly,
  });

  Future<Entry> crateApiEntryGetEntry({required String entryId});

  Future<Feed> crateApiFeedGetFeed({required String feedId});

  String crateApiAppGreet({required String name});

  Future<ImportReport> crateApiOpmlImportOpml({required String xml});

  Future<void> crateApiAppInitApp();

  Future<void> crateApiAppInitDatabase({required String path});

  Future<List<Category>> crateApiEntryListCategories();

  Future<List<EntryListItem>> crateApiEntryListEntries({
    String? feedId,
    required bool unreadOnly,
    required bool starredOnly,
    required int limit,
    required int offset,
  });

  Future<List<Feed>> crateApiFeedListFeeds();

  Future<void> crateApiEntryMarkAllRead({String? feedId});

  Future<void> crateApiEntryMarkEntryRead({
    required String entryId,
    required bool isRead,
  });

  Stream<String> crateApiAppPingStream();

  Stream<SyncProgress> crateApiFeedRefreshAllFeeds();

  Future<SyncReport> crateApiFeedRefreshFeed({required String feedId});

  Future<List<EntryListItem>> crateApiEntrySearchEntries({
    required String query,
    String? feedId,
    required int limit,
  });

  Future<void> crateApiFeedSetFeedViewMode({
    required String feedId,
    required ArticleViewMode viewMode,
  });

  Future<Feed> crateApiFeedSubscribeFeed({required String url});

  Stream<SyncProgress> crateApiFeedSyncFeeds({required List<String> feedIds});

  Future<bool> crateApiEntryToggleEntryStar({required String entryId});

  Future<Feed> crateApiFeedUpdateFeed({
    required String feedId,
    required String title,
    String? siteUrl,
    String? description,
  });

  Future<void> crateApiEntryUpsertCategory({required Category category});

  Future<int> crateApiEntryUpsertEntries({
    required String feedId,
    required List<EntryDraft> drafts,
  });

  Future<void> crateApiFeedUpsertFeed({required Feed feed});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiAppAppVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAppAppVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppAppVersionConstMeta =>
      const TaskConstMeta(debugName: "app_version", argNames: []);

  @override
  Future<ArticleViewMode> crateApiTypesArticleViewModeDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_article_view_mode,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesArticleViewModeDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesArticleViewModeDefaultConstMeta =>
      const TaskConstMeta(debugName: "article_view_mode_default", argNames: []);

  @override
  Future<void> crateApiEntryDeleteCategory({required String categoryId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(categoryId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryDeleteCategoryConstMeta,
        argValues: [categoryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryDeleteCategoryConstMeta =>
      const TaskConstMeta(
        debugName: "delete_category",
        argNames: ["categoryId"],
      );

  @override
  Future<void> crateApiFeedDeleteFeed({required String feedId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(feedId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedDeleteFeedConstMeta,
        argValues: [feedId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedDeleteFeedConstMeta =>
      const TaskConstMeta(debugName: "delete_feed", argNames: ["feedId"]);

  @override
  Future<List<FeedCandidate>> crateApiFeedDiscoverFeeds({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_feed_candidate,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedDiscoverFeedsConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedDiscoverFeedsConstMeta =>
      const TaskConstMeta(debugName: "discover_feeds", argNames: ["url"]);

  @override
  Future<String> crateApiOpmlExportOpml() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiOpmlExportOpmlConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpmlExportOpmlConstMeta =>
      const TaskConstMeta(debugName: "export_opml", argNames: []);

  @override
  Future<AdjacentEntries> crateApiEntryGetAdjacentEntries({
    required String entryId,
    String? feedId,
    required bool unreadOnly,
    required bool starredOnly,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entryId, serializer);
          sse_encode_opt_String(feedId, serializer);
          sse_encode_bool(unreadOnly, serializer);
          sse_encode_bool(starredOnly, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_adjacent_entries,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryGetAdjacentEntriesConstMeta,
        argValues: [entryId, feedId, unreadOnly, starredOnly],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryGetAdjacentEntriesConstMeta =>
      const TaskConstMeta(
        debugName: "get_adjacent_entries",
        argNames: ["entryId", "feedId", "unreadOnly", "starredOnly"],
      );

  @override
  Future<Entry> crateApiEntryGetEntry({required String entryId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entryId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryGetEntryConstMeta,
        argValues: [entryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryGetEntryConstMeta =>
      const TaskConstMeta(debugName: "get_entry", argNames: ["entryId"]);

  @override
  Future<Feed> crateApiFeedGetFeed({required String feedId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(feedId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_feed,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedGetFeedConstMeta,
        argValues: [feedId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedGetFeedConstMeta =>
      const TaskConstMeta(debugName: "get_feed", argNames: ["feedId"]);

  @override
  String crateApiAppGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<ImportReport> crateApiOpmlImportOpml({required String xml}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(xml, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_report,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiOpmlImportOpmlConstMeta,
        argValues: [xml],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpmlImportOpmlConstMeta =>
      const TaskConstMeta(debugName: "import_opml", argNames: ["xml"]);

  @override
  Future<void> crateApiAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiAppInitDatabase({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAppInitDatabaseConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitDatabaseConstMeta =>
      const TaskConstMeta(debugName: "init_database", argNames: ["path"]);

  @override
  Future<List<Category>> crateApiEntryListCategories() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_category,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryListCategoriesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryListCategoriesConstMeta =>
      const TaskConstMeta(debugName: "list_categories", argNames: []);

  @override
  Future<List<EntryListItem>> crateApiEntryListEntries({
    String? feedId,
    required bool unreadOnly,
    required bool starredOnly,
    required int limit,
    required int offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(feedId, serializer);
          sse_encode_bool(unreadOnly, serializer);
          sse_encode_bool(starredOnly, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_u_32(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_entry_list_item,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryListEntriesConstMeta,
        argValues: [feedId, unreadOnly, starredOnly, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryListEntriesConstMeta => const TaskConstMeta(
    debugName: "list_entries",
    argNames: ["feedId", "unreadOnly", "starredOnly", "limit", "offset"],
  );

  @override
  Future<List<Feed>> crateApiFeedListFeeds() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_feed,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedListFeedsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedListFeedsConstMeta =>
      const TaskConstMeta(debugName: "list_feeds", argNames: []);

  @override
  Future<void> crateApiEntryMarkAllRead({String? feedId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(feedId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryMarkAllReadConstMeta,
        argValues: [feedId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryMarkAllReadConstMeta =>
      const TaskConstMeta(debugName: "mark_all_read", argNames: ["feedId"]);

  @override
  Future<void> crateApiEntryMarkEntryRead({
    required String entryId,
    required bool isRead,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entryId, serializer);
          sse_encode_bool(isRead, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryMarkEntryReadConstMeta,
        argValues: [entryId, isRead],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryMarkEntryReadConstMeta => const TaskConstMeta(
    debugName: "mark_entry_read",
    argNames: ["entryId", "isRead"],
  );

  @override
  Stream<String> crateApiAppPingStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 19,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiAppPingStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAppPingStreamConstMeta =>
      const TaskConstMeta(debugName: "ping_stream", argNames: ["sink"]);

  @override
  Stream<SyncProgress> crateApiFeedRefreshAllFeeds() {
    final sink = RustStreamSink<SyncProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_sync_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 20,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_app_error,
          ),
          constMeta: kCrateApiFeedRefreshAllFeedsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFeedRefreshAllFeedsConstMeta =>
      const TaskConstMeta(debugName: "refresh_all_feeds", argNames: ["sink"]);

  @override
  Future<SyncReport> crateApiFeedRefreshFeed({required String feedId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(feedId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_report,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedRefreshFeedConstMeta,
        argValues: [feedId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedRefreshFeedConstMeta =>
      const TaskConstMeta(debugName: "refresh_feed", argNames: ["feedId"]);

  @override
  Future<List<EntryListItem>> crateApiEntrySearchEntries({
    required String query,
    String? feedId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_opt_String(feedId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_entry_list_item,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntrySearchEntriesConstMeta,
        argValues: [query, feedId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntrySearchEntriesConstMeta => const TaskConstMeta(
    debugName: "search_entries",
    argNames: ["query", "feedId", "limit"],
  );

  @override
  Future<void> crateApiFeedSetFeedViewMode({
    required String feedId,
    required ArticleViewMode viewMode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(feedId, serializer);
          sse_encode_article_view_mode(viewMode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedSetFeedViewModeConstMeta,
        argValues: [feedId, viewMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedSetFeedViewModeConstMeta =>
      const TaskConstMeta(
        debugName: "set_feed_view_mode",
        argNames: ["feedId", "viewMode"],
      );

  @override
  Future<Feed> crateApiFeedSubscribeFeed({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_feed,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedSubscribeFeedConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedSubscribeFeedConstMeta =>
      const TaskConstMeta(debugName: "subscribe_feed", argNames: ["url"]);

  @override
  Stream<SyncProgress> crateApiFeedSyncFeeds({required List<String> feedIds}) {
    final sink = RustStreamSink<SyncProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_sync_progress_Sse(sink, serializer);
            sse_encode_list_String(feedIds, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 25,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_app_error,
          ),
          constMeta: kCrateApiFeedSyncFeedsConstMeta,
          argValues: [sink, feedIds],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFeedSyncFeedsConstMeta => const TaskConstMeta(
    debugName: "sync_feeds",
    argNames: ["sink", "feedIds"],
  );

  @override
  Future<bool> crateApiEntryToggleEntryStar({required String entryId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entryId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryToggleEntryStarConstMeta,
        argValues: [entryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryToggleEntryStarConstMeta =>
      const TaskConstMeta(
        debugName: "toggle_entry_star",
        argNames: ["entryId"],
      );

  @override
  Future<Feed> crateApiFeedUpdateFeed({
    required String feedId,
    required String title,
    String? siteUrl,
    String? description,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(feedId, serializer);
          sse_encode_String(title, serializer);
          sse_encode_opt_String(siteUrl, serializer);
          sse_encode_opt_String(description, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_feed,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedUpdateFeedConstMeta,
        argValues: [feedId, title, siteUrl, description],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedUpdateFeedConstMeta => const TaskConstMeta(
    debugName: "update_feed",
    argNames: ["feedId", "title", "siteUrl", "description"],
  );

  @override
  Future<void> crateApiEntryUpsertCategory({required Category category}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_category(category, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryUpsertCategoryConstMeta,
        argValues: [category],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryUpsertCategoryConstMeta =>
      const TaskConstMeta(debugName: "upsert_category", argNames: ["category"]);

  @override
  Future<int> crateApiEntryUpsertEntries({
    required String feedId,
    required List<EntryDraft> drafts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(feedId, serializer);
          sse_encode_list_entry_draft(drafts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiEntryUpsertEntriesConstMeta,
        argValues: [feedId, drafts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryUpsertEntriesConstMeta => const TaskConstMeta(
    debugName: "upsert_entries",
    argNames: ["feedId", "drafts"],
  );

  @override
  Future<void> crateApiFeedUpsertFeed({required Feed feed}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_feed(feed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedUpsertFeedConstMeta,
        argValues: [feed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedUpsertFeedConstMeta =>
      const TaskConstMeta(debugName: "upsert_feed", argNames: ["feed"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SyncProgress> dco_decode_StreamSink_sync_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AdjacentEntries dco_decode_adjacent_entries(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AdjacentEntries(
      prev: dco_decode_opt_String(arr[0]),
      next: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  AppError dco_decode_app_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AppError_NotFound(
          resource: dco_decode_String(raw[1]),
          id: dco_decode_String(raw[2]),
        );
      case 1:
        return AppError_InvalidInput(dco_decode_String(raw[1]));
      case 2:
        return AppError_Network(
          url: dco_decode_String(raw[1]),
          status: dco_decode_u_16(raw[2]),
          message: dco_decode_String(raw[3]),
        );
      case 3:
        return AppError_FeedParse(
          url: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 4:
        return AppError_Database(dco_decode_String(raw[1]));
      case 5:
        return AppError_Io(dco_decode_String(raw[1]));
      case 6:
        return AppError_Unauthorized();
      case 7:
        return AppError_Conflict(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ArticleViewMode dco_decode_article_view_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArticleViewMode.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Chrono_Utc(raw);
  }

  @protected
  Category dco_decode_box_autoadd_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_category(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Feed dco_decode_box_autoadd_feed(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_feed(raw);
  }

  @protected
  Category dco_decode_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Category(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
    );
  }

  @protected
  Entry dco_decode_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return Entry(
      id: dco_decode_String(arr[0]),
      feedId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      url: dco_decode_String(arr[3]),
      content: dco_decode_opt_String(arr[4]),
      summary: dco_decode_opt_String(arr[5]),
      author: dco_decode_opt_String(arr[6]),
      imageUrl: dco_decode_opt_String(arr[7]),
      publishedAt: dco_decode_Chrono_Utc(arr[8]),
      isRead: dco_decode_bool(arr[9]),
      isStarred: dco_decode_bool(arr[10]),
      readProgress: dco_decode_opt_box_autoadd_f_64(arr[11]),
      createdAt: dco_decode_Chrono_Utc(arr[12]),
    );
  }

  @protected
  EntryDraft dco_decode_entry_draft(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return EntryDraft(
      title: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      author: dco_decode_opt_String(arr[2]),
      summary: dco_decode_opt_String(arr[3]),
      content: dco_decode_opt_String(arr[4]),
      publishedAt: dco_decode_opt_box_autoadd_Chrono_Utc(arr[5]),
    );
  }

  @protected
  EntryListItem dco_decode_entry_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return EntryListItem(
      id: dco_decode_String(arr[0]),
      feedId: dco_decode_String(arr[1]),
      feedTitle: dco_decode_String(arr[2]),
      title: dco_decode_String(arr[3]),
      summary: dco_decode_String(arr[4]),
      publishedAt: dco_decode_opt_box_autoadd_Chrono_Utc(arr[5]),
      isRead: dco_decode_bool(arr[6]),
      isStarred: dco_decode_bool(arr[7]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Feed dco_decode_feed(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return Feed(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      sourceUrl: dco_decode_String(arr[2]),
      siteUrl: dco_decode_opt_String(arr[3]),
      description: dco_decode_opt_String(arr[4]),
      imageUrl: dco_decode_opt_String(arr[5]),
      folder: dco_decode_opt_String(arr[6]),
      category: dco_decode_opt_String(arr[7]),
      articleViewMode: dco_decode_article_view_mode(arr[8]),
      unreadCount: dco_decode_i_32(arr[9]),
      articleCount: dco_decode_i_32(arr[10]),
      lastSyncedAt: dco_decode_opt_box_autoadd_Chrono_Utc(arr[11]),
      lastError: dco_decode_opt_String(arr[12]),
      errorCount: dco_decode_i_32(arr[13]),
      etag: dco_decode_opt_String(arr[14]),
      lastModified: dco_decode_opt_String(arr[15]),
      createdAt: dco_decode_Chrono_Utc(arr[16]),
    );
  }

  @protected
  FeedCandidate dco_decode_feed_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FeedCandidate(
      url: dco_decode_String(arr[0]),
      title: dco_decode_opt_String(arr[1]),
      mimeType: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  FeedDraft dco_decode_feed_draft(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FeedDraft(
      title: dco_decode_String(arr[0]),
      sourceUrl: dco_decode_String(arr[1]),
      siteUrl: dco_decode_opt_String(arr[2]),
      description: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImportReport dco_decode_import_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ImportReport(
      total: dco_decode_i_32(arr[0]),
      imported: dco_decode_i_32(arr[1]),
      failed: dco_decode_i_32(arr[2]),
      skipped: dco_decode_i_32(arr[3]),
      failedUrls: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Category> dco_decode_list_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_category).toList();
  }

  @protected
  List<EntryDraft> dco_decode_list_entry_draft(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entry_draft).toList();
  }

  @protected
  List<EntryListItem> dco_decode_list_entry_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entry_list_item).toList();
  }

  @protected
  List<Feed> dco_decode_list_feed(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_feed).toList();
  }

  @protected
  List<FeedCandidate> dco_decode_list_feed_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_feed_candidate).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_Chrono_Utc(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  SyncProgress dco_decode_sync_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SyncProgress(
      total: dco_decode_i_32(arr[0]),
      completed: dco_decode_i_32(arr[1]),
      failed: dco_decode_i_32(arr[2]),
      feedId: dco_decode_opt_String(arr[3]),
      feedTitle: dco_decode_opt_String(arr[4]),
      newEntries: dco_decode_i_32(arr[5]),
      totalNewEntries: dco_decode_i_32(arr[6]),
      done: dco_decode_bool(arr[7]),
      error: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  SyncReport dco_decode_sync_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SyncReport(
      total: dco_decode_i_32(arr[0]),
      completed: dco_decode_i_32(arr[1]),
      failed: dco_decode_i_32(arr[2]),
      newEntries: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SyncProgress> sse_decode_StreamSink_sync_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AdjacentEntries sse_decode_adjacent_entries(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_prev = sse_decode_opt_String(deserializer);
    var var_next = sse_decode_opt_String(deserializer);
    return AdjacentEntries(prev: var_prev, next: var_next);
  }

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_resource = sse_decode_String(deserializer);
        var var_id = sse_decode_String(deserializer);
        return AppError_NotFound(resource: var_resource, id: var_id);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_InvalidInput(var_field0);
      case 2:
        var var_url = sse_decode_String(deserializer);
        var var_status = sse_decode_u_16(deserializer);
        var var_message = sse_decode_String(deserializer);
        return AppError_Network(
          url: var_url,
          status: var_status,
          message: var_message,
        );
      case 3:
        var var_url = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return AppError_FeedParse(url: var_url, message: var_message);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_Database(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_Io(var_field0);
      case 6:
        return AppError_Unauthorized();
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_Conflict(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ArticleViewMode sse_decode_article_view_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ArticleViewMode.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Chrono_Utc(deserializer));
  }

  @protected
  Category sse_decode_box_autoadd_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_category(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  Feed sse_decode_box_autoadd_feed(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_feed(deserializer));
  }

  @protected
  Category sse_decode_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    return Category(id: var_id, title: var_title);
  }

  @protected
  Entry sse_decode_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_feedId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_content = sse_decode_opt_String(deserializer);
    var var_summary = sse_decode_opt_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_imageUrl = sse_decode_opt_String(deserializer);
    var var_publishedAt = sse_decode_Chrono_Utc(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    var var_isStarred = sse_decode_bool(deserializer);
    var var_readProgress = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_createdAt = sse_decode_Chrono_Utc(deserializer);
    return Entry(
      id: var_id,
      feedId: var_feedId,
      title: var_title,
      url: var_url,
      content: var_content,
      summary: var_summary,
      author: var_author,
      imageUrl: var_imageUrl,
      publishedAt: var_publishedAt,
      isRead: var_isRead,
      isStarred: var_isStarred,
      readProgress: var_readProgress,
      createdAt: var_createdAt,
    );
  }

  @protected
  EntryDraft sse_decode_entry_draft(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_summary = sse_decode_opt_String(deserializer);
    var var_content = sse_decode_opt_String(deserializer);
    var var_publishedAt = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    return EntryDraft(
      title: var_title,
      url: var_url,
      author: var_author,
      summary: var_summary,
      content: var_content,
      publishedAt: var_publishedAt,
    );
  }

  @protected
  EntryListItem sse_decode_entry_list_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_feedId = sse_decode_String(deserializer);
    var var_feedTitle = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_publishedAt = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    var var_isStarred = sse_decode_bool(deserializer);
    return EntryListItem(
      id: var_id,
      feedId: var_feedId,
      feedTitle: var_feedTitle,
      title: var_title,
      summary: var_summary,
      publishedAt: var_publishedAt,
      isRead: var_isRead,
      isStarred: var_isStarred,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Feed sse_decode_feed(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_sourceUrl = sse_decode_String(deserializer);
    var var_siteUrl = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_imageUrl = sse_decode_opt_String(deserializer);
    var var_folder = sse_decode_opt_String(deserializer);
    var var_category = sse_decode_opt_String(deserializer);
    var var_articleViewMode = sse_decode_article_view_mode(deserializer);
    var var_unreadCount = sse_decode_i_32(deserializer);
    var var_articleCount = sse_decode_i_32(deserializer);
    var var_lastSyncedAt = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    var var_errorCount = sse_decode_i_32(deserializer);
    var var_etag = sse_decode_opt_String(deserializer);
    var var_lastModified = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_Chrono_Utc(deserializer);
    return Feed(
      id: var_id,
      title: var_title,
      sourceUrl: var_sourceUrl,
      siteUrl: var_siteUrl,
      description: var_description,
      imageUrl: var_imageUrl,
      folder: var_folder,
      category: var_category,
      articleViewMode: var_articleViewMode,
      unreadCount: var_unreadCount,
      articleCount: var_articleCount,
      lastSyncedAt: var_lastSyncedAt,
      lastError: var_lastError,
      errorCount: var_errorCount,
      etag: var_etag,
      lastModified: var_lastModified,
      createdAt: var_createdAt,
    );
  }

  @protected
  FeedCandidate sse_decode_feed_candidate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    return FeedCandidate(
      url: var_url,
      title: var_title,
      mimeType: var_mimeType,
    );
  }

  @protected
  FeedDraft sse_decode_feed_draft(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_sourceUrl = sse_decode_String(deserializer);
    var var_siteUrl = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    return FeedDraft(
      title: var_title,
      sourceUrl: var_sourceUrl,
      siteUrl: var_siteUrl,
      description: var_description,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImportReport sse_decode_import_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_i_32(deserializer);
    var var_imported = sse_decode_i_32(deserializer);
    var var_failed = sse_decode_i_32(deserializer);
    var var_skipped = sse_decode_i_32(deserializer);
    var var_failedUrls = sse_decode_list_String(deserializer);
    return ImportReport(
      total: var_total,
      imported: var_imported,
      failed: var_failed,
      skipped: var_skipped,
      failedUrls: var_failedUrls,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Category> sse_decode_list_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Category>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_category(deserializer));
    }
    return ans_;
  }

  @protected
  List<EntryDraft> sse_decode_list_entry_draft(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EntryDraft>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entry_draft(deserializer));
    }
    return ans_;
  }

  @protected
  List<EntryListItem> sse_decode_list_entry_list_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EntryListItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entry_list_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<Feed> sse_decode_list_feed(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Feed>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_feed(deserializer));
    }
    return ans_;
  }

  @protected
  List<FeedCandidate> sse_decode_list_feed_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FeedCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_feed_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Chrono_Utc(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SyncProgress sse_decode_sync_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_i_32(deserializer);
    var var_completed = sse_decode_i_32(deserializer);
    var var_failed = sse_decode_i_32(deserializer);
    var var_feedId = sse_decode_opt_String(deserializer);
    var var_feedTitle = sse_decode_opt_String(deserializer);
    var var_newEntries = sse_decode_i_32(deserializer);
    var var_totalNewEntries = sse_decode_i_32(deserializer);
    var var_done = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return SyncProgress(
      total: var_total,
      completed: var_completed,
      failed: var_failed,
      feedId: var_feedId,
      feedTitle: var_feedTitle,
      newEntries: var_newEntries,
      totalNewEntries: var_totalNewEntries,
      done: var_done,
      error: var_error,
    );
  }

  @protected
  SyncReport sse_decode_sync_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_i_32(deserializer);
    var var_completed = sse_decode_i_32(deserializer);
    var var_failed = sse_decode_i_32(deserializer);
    var var_newEntries = sse_decode_i_32(deserializer);
    return SyncReport(
      total: var_total,
      completed: var_completed,
      failed: var_failed,
      newEntries: var_newEntries,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(
      PlatformInt64Util.from(self.microsecondsSinceEpoch),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_sync_progress_Sse(
    RustStreamSink<SyncProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_adjacent_entries(
    AdjacentEntries self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.prev, serializer);
    sse_encode_opt_String(self.next, serializer);
  }

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AppError_NotFound(resource: final resource, id: final id):
        sse_encode_i_32(0, serializer);
        sse_encode_String(resource, serializer);
        sse_encode_String(id, serializer);
      case AppError_InvalidInput(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case AppError_Network(
        url: final url,
        status: final status,
        message: final message,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(url, serializer);
        sse_encode_u_16(status, serializer);
        sse_encode_String(message, serializer);
      case AppError_FeedParse(url: final url, message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(url, serializer);
        sse_encode_String(message, serializer);
      case AppError_Database(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case AppError_Io(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case AppError_Unauthorized():
        sse_encode_i_32(6, serializer);
      case AppError_Conflict(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_article_view_mode(
    ArticleViewMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Chrono_Utc(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_category(
    Category self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_category(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_feed(Feed self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_feed(self, serializer);
  }

  @protected
  void sse_encode_category(Category self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
  }

  @protected
  void sse_encode_entry(Entry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.feedId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.content, serializer);
    sse_encode_opt_String(self.summary, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.imageUrl, serializer);
    sse_encode_Chrono_Utc(self.publishedAt, serializer);
    sse_encode_bool(self.isRead, serializer);
    sse_encode_bool(self.isStarred, serializer);
    sse_encode_opt_box_autoadd_f_64(self.readProgress, serializer);
    sse_encode_Chrono_Utc(self.createdAt, serializer);
  }

  @protected
  void sse_encode_entry_draft(EntryDraft self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.summary, serializer);
    sse_encode_opt_String(self.content, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.publishedAt, serializer);
  }

  @protected
  void sse_encode_entry_list_item(
    EntryListItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.feedId, serializer);
    sse_encode_String(self.feedTitle, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.publishedAt, serializer);
    sse_encode_bool(self.isRead, serializer);
    sse_encode_bool(self.isStarred, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_feed(Feed self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.sourceUrl, serializer);
    sse_encode_opt_String(self.siteUrl, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.imageUrl, serializer);
    sse_encode_opt_String(self.folder, serializer);
    sse_encode_opt_String(self.category, serializer);
    sse_encode_article_view_mode(self.articleViewMode, serializer);
    sse_encode_i_32(self.unreadCount, serializer);
    sse_encode_i_32(self.articleCount, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.lastSyncedAt, serializer);
    sse_encode_opt_String(self.lastError, serializer);
    sse_encode_i_32(self.errorCount, serializer);
    sse_encode_opt_String(self.etag, serializer);
    sse_encode_opt_String(self.lastModified, serializer);
    sse_encode_Chrono_Utc(self.createdAt, serializer);
  }

  @protected
  void sse_encode_feed_candidate(FeedCandidate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
  }

  @protected
  void sse_encode_feed_draft(FeedDraft self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.sourceUrl, serializer);
    sse_encode_opt_String(self.siteUrl, serializer);
    sse_encode_opt_String(self.description, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_import_report(ImportReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.total, serializer);
    sse_encode_i_32(self.imported, serializer);
    sse_encode_i_32(self.failed, serializer);
    sse_encode_i_32(self.skipped, serializer);
    sse_encode_list_String(self.failedUrls, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_category(List<Category> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_category(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entry_draft(
    List<EntryDraft> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entry_draft(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entry_list_item(
    List<EntryListItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entry_list_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_feed(List<Feed> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_feed(item, serializer);
    }
  }

  @protected
  void sse_encode_list_feed_candidate(
    List<FeedCandidate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_feed_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Chrono_Utc(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_sync_progress(SyncProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.total, serializer);
    sse_encode_i_32(self.completed, serializer);
    sse_encode_i_32(self.failed, serializer);
    sse_encode_opt_String(self.feedId, serializer);
    sse_encode_opt_String(self.feedTitle, serializer);
    sse_encode_i_32(self.newEntries, serializer);
    sse_encode_i_32(self.totalNewEntries, serializer);
    sse_encode_bool(self.done, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_sync_report(SyncReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.total, serializer);
    sse_encode_i_32(self.completed, serializer);
    sse_encode_i_32(self.failed, serializer);
    sse_encode_i_32(self.newEntries, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
