// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ai.dart';
import 'api/app.dart';
import 'api/entry.dart';
import 'api/error.dart';
import 'api/feed.dart';
import 'api/opml.dart';
import 'api/settings.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<SyncProgress> dco_decode_StreamSink_sync_progress_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AdjacentEntries dco_decode_adjacent_entries(dynamic raw);

  @protected
  AiConfig dco_decode_ai_config(dynamic raw);

  @protected
  AiViewMode dco_decode_ai_view_mode(dynamic raw);

  @protected
  AppError dco_decode_app_error(dynamic raw);

  @protected
  ArticleViewMode dco_decode_article_view_mode(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  AiConfig dco_decode_box_autoadd_ai_config(dynamic raw);

  @protected
  Category dco_decode_box_autoadd_category(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  Feed dco_decode_box_autoadd_feed(dynamic raw);

  @protected
  Category dco_decode_category(dynamic raw);

  @protected
  Entry dco_decode_entry(dynamic raw);

  @protected
  EntryDraft dco_decode_entry_draft(dynamic raw);

  @protected
  EntryListItem dco_decode_entry_list_item(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Feed dco_decode_feed(dynamic raw);

  @protected
  FeedCandidate dco_decode_feed_candidate(dynamic raw);

  @protected
  FeedDraft dco_decode_feed_draft(dynamic raw);

  @protected
  FeedType dco_decode_feed_type(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportReport dco_decode_import_report(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Category> dco_decode_list_category(dynamic raw);

  @protected
  List<EntryDraft> dco_decode_list_entry_draft(dynamic raw);

  @protected
  List<EntryListItem> dco_decode_list_entry_list_item(dynamic raw);

  @protected
  List<Feed> dco_decode_list_feed(dynamic raw);

  @protected
  List<FeedCandidate> dco_decode_list_feed_candidate(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  SyncProgress dco_decode_sync_progress(dynamic raw);

  @protected
  SyncReport dco_decode_sync_report(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncProgress> sse_decode_StreamSink_sync_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdjacentEntries sse_decode_adjacent_entries(SseDeserializer deserializer);

  @protected
  AiConfig sse_decode_ai_config(SseDeserializer deserializer);

  @protected
  AiViewMode sse_decode_ai_view_mode(SseDeserializer deserializer);

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer);

  @protected
  ArticleViewMode sse_decode_article_view_mode(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  AiConfig sse_decode_box_autoadd_ai_config(SseDeserializer deserializer);

  @protected
  Category sse_decode_box_autoadd_category(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  Feed sse_decode_box_autoadd_feed(SseDeserializer deserializer);

  @protected
  Category sse_decode_category(SseDeserializer deserializer);

  @protected
  Entry sse_decode_entry(SseDeserializer deserializer);

  @protected
  EntryDraft sse_decode_entry_draft(SseDeserializer deserializer);

  @protected
  EntryListItem sse_decode_entry_list_item(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Feed sse_decode_feed(SseDeserializer deserializer);

  @protected
  FeedCandidate sse_decode_feed_candidate(SseDeserializer deserializer);

  @protected
  FeedDraft sse_decode_feed_draft(SseDeserializer deserializer);

  @protected
  FeedType sse_decode_feed_type(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportReport sse_decode_import_report(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Category> sse_decode_list_category(SseDeserializer deserializer);

  @protected
  List<EntryDraft> sse_decode_list_entry_draft(SseDeserializer deserializer);

  @protected
  List<EntryListItem> sse_decode_list_entry_list_item(
    SseDeserializer deserializer,
  );

  @protected
  List<Feed> sse_decode_list_feed(SseDeserializer deserializer);

  @protected
  List<FeedCandidate> sse_decode_list_feed_candidate(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  SyncProgress sse_decode_sync_progress(SseDeserializer deserializer);

  @protected
  SyncReport sse_decode_sync_report(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_progress_Sse(
    RustStreamSink<SyncProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_adjacent_entries(
    AdjacentEntries self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_config(AiConfig self, SseSerializer serializer);

  @protected
  void sse_encode_ai_view_mode(AiViewMode self, SseSerializer serializer);

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer);

  @protected
  void sse_encode_article_view_mode(
    ArticleViewMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ai_config(
    AiConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_category(Category self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_feed(Feed self, SseSerializer serializer);

  @protected
  void sse_encode_category(Category self, SseSerializer serializer);

  @protected
  void sse_encode_entry(Entry self, SseSerializer serializer);

  @protected
  void sse_encode_entry_draft(EntryDraft self, SseSerializer serializer);

  @protected
  void sse_encode_entry_list_item(EntryListItem self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_feed(Feed self, SseSerializer serializer);

  @protected
  void sse_encode_feed_candidate(FeedCandidate self, SseSerializer serializer);

  @protected
  void sse_encode_feed_draft(FeedDraft self, SseSerializer serializer);

  @protected
  void sse_encode_feed_type(FeedType self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_report(ImportReport self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_category(List<Category> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entry_draft(
    List<EntryDraft> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_list_item(
    List<EntryListItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_feed(List<Feed> self, SseSerializer serializer);

  @protected
  void sse_encode_list_feed_candidate(
    List<FeedCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_sync_progress(SyncProgress self, SseSerializer serializer);

  @protected
  void sse_encode_sync_report(SyncReport self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
