// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/error.dart';
import 'api/reader.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAppInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -919766935;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_rss_reader',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiReaderAddFeed({
    required String snapshotJson,
    required FeedDraft draft,
  });

  String crateApiAppAppVersion();

  Future<ArticleViewMode> crateApiReaderArticleViewModeDefault();

  String crateApiReaderClearAllReadArticles({required String snapshotJson});

  ReaderSnapshot crateApiReaderDecodeReaderSnapshot({
    required String snapshotJson,
  });

  String crateApiReaderEmptyReaderSnapshotJson();

  Article crateApiReaderGetArticle({
    required String snapshotJson,
    required String articleId,
  });

  String crateApiAppGreet({required String name});

  Future<ImportFeedResult> crateApiReaderImportFeedFromXml({
    required String snapshotJson,
    required String feedUrl,
    required String xmlContent,
  });

  Future<void> crateApiAppInitApp();

  List<ArticleListItem> crateApiReaderListArticles({
    required String snapshotJson,
    String? feedId,
    required bool showStarredOnly,
    required bool showUnreadOnly,
  });

  String crateApiReaderMarkArticleRead({
    required String snapshotJson,
    required String articleId,
    required bool isRead,
  });

  String crateApiReaderRecordFeedError({
    required String snapshotJson,
    required String feedId,
    required String errorMessage,
  });

  String crateApiReaderRemoveFeed({
    required String snapshotJson,
    required String feedId,
  });

  String crateApiReaderSetFeedViewMode({
    required String snapshotJson,
    required String feedId,
    required ArticleViewMode viewMode,
  });

  String crateApiReaderToggleArticleStar({
    required String snapshotJson,
    required String articleId,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiReaderAddFeed({
    required String snapshotJson,
    required FeedDraft draft,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_box_autoadd_feed_draft(draft, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderAddFeedConstMeta,
        argValues: [snapshotJson, draft],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderAddFeedConstMeta => const TaskConstMeta(
    debugName: "add_feed",
    argNames: ["snapshotJson", "draft"],
  );

  @override
  String crateApiAppAppVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAppAppVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppAppVersionConstMeta =>
      const TaskConstMeta(debugName: "app_version", argNames: []);

  @override
  Future<ArticleViewMode> crateApiReaderArticleViewModeDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_article_view_mode,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReaderArticleViewModeDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderArticleViewModeDefaultConstMeta =>
      const TaskConstMeta(debugName: "article_view_mode_default", argNames: []);

  @override
  String crateApiReaderClearAllReadArticles({required String snapshotJson}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderClearAllReadArticlesConstMeta,
        argValues: [snapshotJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderClearAllReadArticlesConstMeta =>
      const TaskConstMeta(
        debugName: "clear_all_read_articles",
        argNames: ["snapshotJson"],
      );

  @override
  ReaderSnapshot crateApiReaderDecodeReaderSnapshot({
    required String snapshotJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_reader_snapshot,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderDecodeReaderSnapshotConstMeta,
        argValues: [snapshotJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderDecodeReaderSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "decode_reader_snapshot",
        argNames: ["snapshotJson"],
      );

  @override
  String crateApiReaderEmptyReaderSnapshotJson() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReaderEmptyReaderSnapshotJsonConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderEmptyReaderSnapshotJsonConstMeta =>
      const TaskConstMeta(
        debugName: "empty_reader_snapshot_json",
        argNames: [],
      );

  @override
  Article crateApiReaderGetArticle({
    required String snapshotJson,
    required String articleId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(articleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_article,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderGetArticleConstMeta,
        argValues: [snapshotJson, articleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderGetArticleConstMeta => const TaskConstMeta(
    debugName: "get_article",
    argNames: ["snapshotJson", "articleId"],
  );

  @override
  String crateApiAppGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<ImportFeedResult> crateApiReaderImportFeedFromXml({
    required String snapshotJson,
    required String feedUrl,
    required String xmlContent,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(feedUrl, serializer);
          sse_encode_String(xmlContent, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_feed_result,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderImportFeedFromXmlConstMeta,
        argValues: [snapshotJson, feedUrl, xmlContent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderImportFeedFromXmlConstMeta =>
      const TaskConstMeta(
        debugName: "import_feed_from_xml",
        argNames: ["snapshotJson", "feedUrl", "xmlContent"],
      );

  @override
  Future<void> crateApiAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<ArticleListItem> crateApiReaderListArticles({
    required String snapshotJson,
    String? feedId,
    required bool showStarredOnly,
    required bool showUnreadOnly,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_opt_String(feedId, serializer);
          sse_encode_bool(showStarredOnly, serializer);
          sse_encode_bool(showUnreadOnly, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_article_list_item,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderListArticlesConstMeta,
        argValues: [snapshotJson, feedId, showStarredOnly, showUnreadOnly],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderListArticlesConstMeta => const TaskConstMeta(
    debugName: "list_articles",
    argNames: ["snapshotJson", "feedId", "showStarredOnly", "showUnreadOnly"],
  );

  @override
  String crateApiReaderMarkArticleRead({
    required String snapshotJson,
    required String articleId,
    required bool isRead,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(articleId, serializer);
          sse_encode_bool(isRead, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderMarkArticleReadConstMeta,
        argValues: [snapshotJson, articleId, isRead],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderMarkArticleReadConstMeta =>
      const TaskConstMeta(
        debugName: "mark_article_read",
        argNames: ["snapshotJson", "articleId", "isRead"],
      );

  @override
  String crateApiReaderRecordFeedError({
    required String snapshotJson,
    required String feedId,
    required String errorMessage,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(feedId, serializer);
          sse_encode_String(errorMessage, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderRecordFeedErrorConstMeta,
        argValues: [snapshotJson, feedId, errorMessage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderRecordFeedErrorConstMeta =>
      const TaskConstMeta(
        debugName: "record_feed_error",
        argNames: ["snapshotJson", "feedId", "errorMessage"],
      );

  @override
  String crateApiReaderRemoveFeed({
    required String snapshotJson,
    required String feedId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(feedId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderRemoveFeedConstMeta,
        argValues: [snapshotJson, feedId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderRemoveFeedConstMeta => const TaskConstMeta(
    debugName: "remove_feed",
    argNames: ["snapshotJson", "feedId"],
  );

  @override
  String crateApiReaderSetFeedViewMode({
    required String snapshotJson,
    required String feedId,
    required ArticleViewMode viewMode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(feedId, serializer);
          sse_encode_article_view_mode(viewMode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderSetFeedViewModeConstMeta,
        argValues: [snapshotJson, feedId, viewMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderSetFeedViewModeConstMeta =>
      const TaskConstMeta(
        debugName: "set_feed_view_mode",
        argNames: ["snapshotJson", "feedId", "viewMode"],
      );

  @override
  String crateApiReaderToggleArticleStar({
    required String snapshotJson,
    required String articleId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(articleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderToggleArticleStarConstMeta,
        argValues: [snapshotJson, articleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderToggleArticleStarConstMeta =>
      const TaskConstMeta(
        debugName: "toggle_article_star",
        argNames: ["snapshotJson", "articleId"],
      );

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppError dco_decode_app_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AppError_NotFound(
          resource: dco_decode_String(raw[1]),
          id: dco_decode_String(raw[2]),
        );
      case 1:
        return AppError_InvalidInput(dco_decode_String(raw[1]));
      case 2:
        return AppError_Network(
          url: dco_decode_String(raw[1]),
          status: dco_decode_u_16(raw[2]),
          message: dco_decode_String(raw[3]),
        );
      case 3:
        return AppError_FeedParse(
          url: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 4:
        return AppError_Database(dco_decode_String(raw[1]));
      case 5:
        return AppError_Io(dco_decode_String(raw[1]));
      case 6:
        return AppError_Unauthorized();
      case 7:
        return AppError_Conflict(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  Article dco_decode_article(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Article(
      id: dco_decode_String(arr[0]),
      feedId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      url: dco_decode_String(arr[3]),
      author: dco_decode_String(arr[4]),
      summary: dco_decode_String(arr[5]),
      content: dco_decode_String(arr[6]),
      publishedAt: dco_decode_opt_String(arr[7]),
      isRead: dco_decode_bool(arr[8]),
      isStarred: dco_decode_bool(arr[9]),
    );
  }

  @protected
  ArticleListItem dco_decode_article_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ArticleListItem(
      id: dco_decode_String(arr[0]),
      feedId: dco_decode_String(arr[1]),
      feedTitle: dco_decode_String(arr[2]),
      title: dco_decode_String(arr[3]),
      summary: dco_decode_String(arr[4]),
      publishedAt: dco_decode_opt_String(arr[5]),
      isRead: dco_decode_bool(arr[6]),
      isStarred: dco_decode_bool(arr[7]),
    );
  }

  @protected
  ArticleViewMode dco_decode_article_view_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArticleViewMode.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Chrono_Utc(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FeedDraft dco_decode_box_autoadd_feed_draft(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_feed_draft(raw);
  }

  @protected
  Category dco_decode_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Category(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
    );
  }

  @protected
  Entry dco_decode_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return Entry(
      id: dco_decode_String(arr[0]),
      feedId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      url: dco_decode_String(arr[3]),
      content: dco_decode_opt_String(arr[4]),
      summary: dco_decode_opt_String(arr[5]),
      author: dco_decode_opt_String(arr[6]),
      imageUrl: dco_decode_opt_String(arr[7]),
      publishedAt: dco_decode_Chrono_Utc(arr[8]),
      isRead: dco_decode_bool(arr[9]),
      isStarred: dco_decode_bool(arr[10]),
      readProgress: dco_decode_opt_box_autoadd_f_64(arr[11]),
      createdAt: dco_decode_Chrono_Utc(arr[12]),
    );
  }

  @protected
  EntryDraft dco_decode_entry_draft(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return EntryDraft(
      title: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      author: dco_decode_opt_String(arr[2]),
      summary: dco_decode_opt_String(arr[3]),
      content: dco_decode_opt_String(arr[4]),
      publishedAt: dco_decode_opt_box_autoadd_Chrono_Utc(arr[5]),
    );
  }

  @protected
  EntryListItem dco_decode_entry_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return EntryListItem(
      id: dco_decode_String(arr[0]),
      feedId: dco_decode_String(arr[1]),
      feedTitle: dco_decode_String(arr[2]),
      title: dco_decode_String(arr[3]),
      summary: dco_decode_String(arr[4]),
      publishedAt: dco_decode_opt_box_autoadd_Chrono_Utc(arr[5]),
      isRead: dco_decode_bool(arr[6]),
      isStarred: dco_decode_bool(arr[7]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Feed dco_decode_feed(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return Feed(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      sourceUrl: dco_decode_String(arr[2]),
      siteUrl: dco_decode_String(arr[3]),
      description: dco_decode_String(arr[4]),
      unreadCount: dco_decode_i_32(arr[5]),
      articleCount: dco_decode_i_32(arr[6]),
      lastSyncedAt: dco_decode_opt_String(arr[7]),
      articleViewMode: dco_decode_article_view_mode(arr[8]),
      lastError: dco_decode_opt_String(arr[9]),
      errorCount: dco_decode_i_32(arr[10]),
    );
  }

  @protected
  FeedDraft dco_decode_feed_draft(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FeedDraft(
      title: dco_decode_String(arr[0]),
      sourceUrl: dco_decode_String(arr[1]),
      siteUrl: dco_decode_String(arr[2]),
      description: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImportFeedResult dco_decode_import_feed_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ImportFeedResult(
      snapshotJson: dco_decode_String(arr[0]),
      feed: dco_decode_feed(arr[1]),
      insertedArticles: dco_decode_list_article(arr[2]),
    );
  }

  @protected
  List<Article> dco_decode_list_article(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_article).toList();
  }

  @protected
  List<ArticleListItem> dco_decode_list_article_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_article_list_item).toList();
  }

  @protected
  List<Feed> dco_decode_list_feed(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_feed).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_Chrono_Utc(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  ReaderError dco_decode_reader_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ReaderError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  ReaderSnapshot dco_decode_reader_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ReaderSnapshot(
      feeds: dco_decode_list_feed(arr[0]),
      articles: dco_decode_list_article(arr[1]),
      lastUpdatedAt: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SyncProgress dco_decode_sync_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SyncProgress(
      total: dco_decode_i_32(arr[0]),
      completed: dco_decode_i_32(arr[1]),
      feedId: dco_decode_opt_String(arr[2]),
      newEntries: dco_decode_i_32(arr[3]),
      done: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_resource = sse_decode_String(deserializer);
        var var_id = sse_decode_String(deserializer);
        return AppError_NotFound(resource: var_resource, id: var_id);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_InvalidInput(var_field0);
      case 2:
        var var_url = sse_decode_String(deserializer);
        var var_status = sse_decode_u_16(deserializer);
        var var_message = sse_decode_String(deserializer);
        return AppError_Network(
          url: var_url,
          status: var_status,
          message: var_message,
        );
      case 3:
        var var_url = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return AppError_FeedParse(url: var_url, message: var_message);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_Database(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_Io(var_field0);
      case 6:
        return AppError_Unauthorized();
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_Conflict(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  Article sse_decode_article(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_feedId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_publishedAt = sse_decode_opt_String(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    var var_isStarred = sse_decode_bool(deserializer);
    return Article(
      id: var_id,
      feedId: var_feedId,
      title: var_title,
      url: var_url,
      author: var_author,
      summary: var_summary,
      content: var_content,
      publishedAt: var_publishedAt,
      isRead: var_isRead,
      isStarred: var_isStarred,
    );
  }

  @protected
  ArticleListItem sse_decode_article_list_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_feedId = sse_decode_String(deserializer);
    var var_feedTitle = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_publishedAt = sse_decode_opt_String(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    var var_isStarred = sse_decode_bool(deserializer);
    return ArticleListItem(
      id: var_id,
      feedId: var_feedId,
      feedTitle: var_feedTitle,
      title: var_title,
      summary: var_summary,
      publishedAt: var_publishedAt,
      isRead: var_isRead,
      isStarred: var_isStarred,
    );
  }

  @protected
  ArticleViewMode sse_decode_article_view_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ArticleViewMode.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Chrono_Utc(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  FeedDraft sse_decode_box_autoadd_feed_draft(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_feed_draft(deserializer));
  }

  @protected
  Category sse_decode_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    return Category(id: var_id, title: var_title);
  }

  @protected
  Entry sse_decode_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_feedId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_content = sse_decode_opt_String(deserializer);
    var var_summary = sse_decode_opt_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_imageUrl = sse_decode_opt_String(deserializer);
    var var_publishedAt = sse_decode_Chrono_Utc(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    var var_isStarred = sse_decode_bool(deserializer);
    var var_readProgress = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_createdAt = sse_decode_Chrono_Utc(deserializer);
    return Entry(
      id: var_id,
      feedId: var_feedId,
      title: var_title,
      url: var_url,
      content: var_content,
      summary: var_summary,
      author: var_author,
      imageUrl: var_imageUrl,
      publishedAt: var_publishedAt,
      isRead: var_isRead,
      isStarred: var_isStarred,
      readProgress: var_readProgress,
      createdAt: var_createdAt,
    );
  }

  @protected
  EntryDraft sse_decode_entry_draft(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_summary = sse_decode_opt_String(deserializer);
    var var_content = sse_decode_opt_String(deserializer);
    var var_publishedAt = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    return EntryDraft(
      title: var_title,
      url: var_url,
      author: var_author,
      summary: var_summary,
      content: var_content,
      publishedAt: var_publishedAt,
    );
  }

  @protected
  EntryListItem sse_decode_entry_list_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_feedId = sse_decode_String(deserializer);
    var var_feedTitle = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_publishedAt = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    var var_isStarred = sse_decode_bool(deserializer);
    return EntryListItem(
      id: var_id,
      feedId: var_feedId,
      feedTitle: var_feedTitle,
      title: var_title,
      summary: var_summary,
      publishedAt: var_publishedAt,
      isRead: var_isRead,
      isStarred: var_isStarred,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Feed sse_decode_feed(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_sourceUrl = sse_decode_String(deserializer);
    var var_siteUrl = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_unreadCount = sse_decode_i_32(deserializer);
    var var_articleCount = sse_decode_i_32(deserializer);
    var var_lastSyncedAt = sse_decode_opt_String(deserializer);
    var var_articleViewMode = sse_decode_article_view_mode(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    var var_errorCount = sse_decode_i_32(deserializer);
    return Feed(
      id: var_id,
      title: var_title,
      sourceUrl: var_sourceUrl,
      siteUrl: var_siteUrl,
      description: var_description,
      unreadCount: var_unreadCount,
      articleCount: var_articleCount,
      lastSyncedAt: var_lastSyncedAt,
      articleViewMode: var_articleViewMode,
      lastError: var_lastError,
      errorCount: var_errorCount,
    );
  }

  @protected
  FeedDraft sse_decode_feed_draft(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_sourceUrl = sse_decode_String(deserializer);
    var var_siteUrl = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return FeedDraft(
      title: var_title,
      sourceUrl: var_sourceUrl,
      siteUrl: var_siteUrl,
      description: var_description,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImportFeedResult sse_decode_import_feed_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_snapshotJson = sse_decode_String(deserializer);
    var var_feed = sse_decode_feed(deserializer);
    var var_insertedArticles = sse_decode_list_article(deserializer);
    return ImportFeedResult(
      snapshotJson: var_snapshotJson,
      feed: var_feed,
      insertedArticles: var_insertedArticles,
    );
  }

  @protected
  List<Article> sse_decode_list_article(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Article>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_article(deserializer));
    }
    return ans_;
  }

  @protected
  List<ArticleListItem> sse_decode_list_article_list_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ArticleListItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_article_list_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<Feed> sse_decode_list_feed(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Feed>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_feed(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Chrono_Utc(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReaderError sse_decode_reader_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ReaderError(code: var_code, message: var_message);
  }

  @protected
  ReaderSnapshot sse_decode_reader_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_feeds = sse_decode_list_feed(deserializer);
    var var_articles = sse_decode_list_article(deserializer);
    var var_lastUpdatedAt = sse_decode_opt_String(deserializer);
    return ReaderSnapshot(
      feeds: var_feeds,
      articles: var_articles,
      lastUpdatedAt: var_lastUpdatedAt,
    );
  }

  @protected
  SyncProgress sse_decode_sync_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_i_32(deserializer);
    var var_completed = sse_decode_i_32(deserializer);
    var var_feedId = sse_decode_opt_String(deserializer);
    var var_newEntries = sse_decode_i_32(deserializer);
    var var_done = sse_decode_bool(deserializer);
    return SyncProgress(
      total: var_total,
      completed: var_completed,
      feedId: var_feedId,
      newEntries: var_newEntries,
      done: var_done,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(
      PlatformInt64Util.from(self.microsecondsSinceEpoch),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AppError_NotFound(resource: final resource, id: final id):
        sse_encode_i_32(0, serializer);
        sse_encode_String(resource, serializer);
        sse_encode_String(id, serializer);
      case AppError_InvalidInput(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case AppError_Network(
        url: final url,
        status: final status,
        message: final message,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(url, serializer);
        sse_encode_u_16(status, serializer);
        sse_encode_String(message, serializer);
      case AppError_FeedParse(url: final url, message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(url, serializer);
        sse_encode_String(message, serializer);
      case AppError_Database(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case AppError_Io(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case AppError_Unauthorized():
        sse_encode_i_32(6, serializer);
      case AppError_Conflict(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_article(Article self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.feedId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_opt_String(self.publishedAt, serializer);
    sse_encode_bool(self.isRead, serializer);
    sse_encode_bool(self.isStarred, serializer);
  }

  @protected
  void sse_encode_article_list_item(
    ArticleListItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.feedId, serializer);
    sse_encode_String(self.feedTitle, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_opt_String(self.publishedAt, serializer);
    sse_encode_bool(self.isRead, serializer);
    sse_encode_bool(self.isStarred, serializer);
  }

  @protected
  void sse_encode_article_view_mode(
    ArticleViewMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Chrono_Utc(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_feed_draft(
    FeedDraft self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_feed_draft(self, serializer);
  }

  @protected
  void sse_encode_category(Category self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
  }

  @protected
  void sse_encode_entry(Entry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.feedId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.content, serializer);
    sse_encode_opt_String(self.summary, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.imageUrl, serializer);
    sse_encode_Chrono_Utc(self.publishedAt, serializer);
    sse_encode_bool(self.isRead, serializer);
    sse_encode_bool(self.isStarred, serializer);
    sse_encode_opt_box_autoadd_f_64(self.readProgress, serializer);
    sse_encode_Chrono_Utc(self.createdAt, serializer);
  }

  @protected
  void sse_encode_entry_draft(EntryDraft self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.summary, serializer);
    sse_encode_opt_String(self.content, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.publishedAt, serializer);
  }

  @protected
  void sse_encode_entry_list_item(
    EntryListItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.feedId, serializer);
    sse_encode_String(self.feedTitle, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.publishedAt, serializer);
    sse_encode_bool(self.isRead, serializer);
    sse_encode_bool(self.isStarred, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_feed(Feed self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.sourceUrl, serializer);
    sse_encode_String(self.siteUrl, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_i_32(self.unreadCount, serializer);
    sse_encode_i_32(self.articleCount, serializer);
    sse_encode_opt_String(self.lastSyncedAt, serializer);
    sse_encode_article_view_mode(self.articleViewMode, serializer);
    sse_encode_opt_String(self.lastError, serializer);
    sse_encode_i_32(self.errorCount, serializer);
  }

  @protected
  void sse_encode_feed_draft(FeedDraft self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.sourceUrl, serializer);
    sse_encode_String(self.siteUrl, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_import_feed_result(
    ImportFeedResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.snapshotJson, serializer);
    sse_encode_feed(self.feed, serializer);
    sse_encode_list_article(self.insertedArticles, serializer);
  }

  @protected
  void sse_encode_list_article(List<Article> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_article(item, serializer);
    }
  }

  @protected
  void sse_encode_list_article_list_item(
    List<ArticleListItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_article_list_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_feed(List<Feed> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_feed(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Chrono_Utc(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_reader_error(ReaderError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_reader_snapshot(
    ReaderSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_feed(self.feeds, serializer);
    sse_encode_list_article(self.articles, serializer);
    sse_encode_opt_String(self.lastUpdatedAt, serializer);
  }

  @protected
  void sse_encode_sync_progress(SyncProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.total, serializer);
    sse_encode_i_32(self.completed, serializer);
    sse_encode_opt_String(self.feedId, serializer);
    sse_encode_i_32(self.newEntries, serializer);
    sse_encode_bool(self.done, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
