// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Generates a concise AI summary for `entry_id` in the configured target
/// language. Returns the cached value from the database if one exists.
Future<String> summarizeEntry({required String entryId}) =>
    RustLib.instance.api.crateApiAiSummarizeEntry(entryId: entryId);

/// Translates `entry_id` into `target_language`. Returns the cached value from
/// the database if one exists.
Future<String> translateEntry({
  required String entryId,
  required String targetLanguage,
}) => RustLib.instance.api.crateApiAiTranslateEntry(
  entryId: entryId,
  targetLanguage: targetLanguage,
);

/// Returns the configured AI provider, with defaults for unset keys.
Future<AiConfig> getAiConfig() => RustLib.instance.api.crateApiAiGetAiConfig();

/// Persists the AI provider configuration.
Future<void> setAiConfig({required AiConfig config}) =>
    RustLib.instance.api.crateApiAiSetAiConfig(config: config);
