// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Demo sync function (kept from the original `simple.rs` scaffold).
String greet({required String name}) =>
    RustLib.instance.api.crateApiAppGreet(name: name);

/// Opens the SQLite database at `path`, applies pragmas (WAL / foreign_keys /
/// synchronous), runs pending migrations, and stores the shared connection.
///
/// Plain `pub fn` (no `#[frb(sync)]`) so it runs on the FRB worker thread pool
/// and never blocks the Flutter UI isolate. Dart calls `await initDatabase(path)`
/// once after `RustLib.init()`.
Future<void> initDatabase({required String path}) =>
    RustLib.instance.api.crateApiAppInitDatabase(path: path);

/// Returns the Rust crate version. Also serves as the codegen smoke-test that
/// ensures `AppError` is generated as a throwable Dart enum.
String appVersion() => RustLib.instance.api.crateApiAppAppVersion();

/// StreamSink smoke test (P1b). The first function in the crate to use FRB
/// streaming — verifies the `SseCodec` `StreamSink<T>` path end-to-end before
/// the feed-sync stream is built on top of it. Emits three `ping N` strings
/// then closes. Dart side receives a `Stream<String>`. Kept as a tiny
/// diagnostic helper; safe to remove once streaming is proven in production.
Stream<String> pingStream() => RustLib.instance.api.crateApiAppPingStream();
