// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Lists entries as lightweight list items, optionally filtered by feed,
/// unread, and/or starred state. Results are newest-first (`published_at DESC`)
/// and paginated by `limit`/`offset`.
Future<List<EntryListItem>> listEntries({
  String? feedId,
  required bool unreadOnly,
  required bool starredOnly,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateApiEntryListEntries(
  feedId: feedId,
  unreadOnly: unreadOnly,
  starredOnly: starredOnly,
  limit: limit,
  offset: offset,
);

/// Returns a single entry by id, or `NotFound` if missing.
Future<Entry> getEntry({required String entryId}) =>
    RustLib.instance.api.crateApiEntryGetEntry(entryId: entryId);

/// Sets an entry's read state and recomputes the parent feed's cached
/// `unread_count`. `NotFound` if the entry does not exist.
Future<void> markEntryRead({required String entryId, required bool isRead}) =>
    RustLib.instance.api.crateApiEntryMarkEntryRead(
      entryId: entryId,
      isRead: isRead,
    );

/// Toggles an entry's starred flag and returns the new starred state.
/// `NotFound` if the entry does not exist.
Future<bool> toggleEntryStar({required String entryId}) =>
    RustLib.instance.api.crateApiEntryToggleEntryStar(entryId: entryId);

/// Returns the previous (newer) and next (older) entry ids relative to
/// `entry_id`, within the same filter context used by the entry list. Used by
/// the reading UI for prev/next navigation.
Future<AdjacentEntries> getAdjacentEntries({
  required String entryId,
  String? feedId,
  required bool unreadOnly,
  required bool starredOnly,
}) => RustLib.instance.api.crateApiEntryGetAdjacentEntries(
  entryId: entryId,
  feedId: feedId,
  unreadOnly: unreadOnly,
  starredOnly: starredOnly,
);

/// Inserts new entries for a feed, deduplicating by URL within the feed.
/// Returns the number of entries actually inserted.
Future<int> upsertEntries({
  required String feedId,
  required List<EntryDraft> drafts,
}) => RustLib.instance.api.crateApiEntryUpsertEntries(
  feedId: feedId,
  drafts: drafts,
);

/// Searches entries by `LIKE %query%` on title + summary + content (parity
/// with Livo's `entry-repository.searchEntries`). Case-insensitive. Optional
/// `feed_id` scopes the search to one feed; `None` searches all feeds.
/// Results are newest-first and capped by `limit`. An empty/whitespace query
/// returns an empty list (no error).
Future<List<EntryListItem>> searchEntries({
  required String query,
  String? feedId,
  required int limit,
}) => RustLib.instance.api.crateApiEntrySearchEntries(
  query: query,
  feedId: feedId,
  limit: limit,
);

/// Marks all entries as read, optionally scoped to one feed.
Future<void> markAllRead({String? feedId}) =>
    RustLib.instance.api.crateApiEntryMarkAllRead(feedId: feedId);

Future<List<Category>> listCategories() =>
    RustLib.instance.api.crateApiEntryListCategories();

Future<void> upsertCategory({required Category category}) =>
    RustLib.instance.api.crateApiEntryUpsertCategory(category: category);

Future<void> deleteCategory({required String categoryId}) =>
    RustLib.instance.api.crateApiEntryDeleteCategory(categoryId: categoryId);
