// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `database`, `invalid_input`, `not_found`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

@freezed
sealed class AppError with _$AppError implements FrbException {
  const AppError._();

  /// A resource (feed, entry, category, ...) was not found.
  const factory AppError.notFound({
    required String resource,
    required String id,
  }) = AppError_NotFound;

  /// User-supplied input was invalid (empty URL, duplicate subscription, ...).
  const factory AppError.invalidInput(String field0) = AppError_InvalidInput;

  /// A network request failed.
  const factory AppError.network({
    required String url,
    required int status,
    required String message,
  }) = AppError_Network;

  /// A feed could not be parsed (unsupported format, malformed XML, ...).
  const factory AppError.feedParse({
    required String url,
    required String message,
  }) = AppError_FeedParse;

  /// A database operation failed.
  const factory AppError.database(String field0) = AppError_Database;

  /// An I/O operation failed.
  const factory AppError.io(String field0) = AppError_Io;

  /// Authentication is required or has expired.
  const factory AppError.unauthorized() = AppError_Unauthorized;

  /// A write conflicts with existing state (duplicate insert, ...).
  const factory AppError.conflict(String field0) = AppError_Conflict;
}
