// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'reader.dart';
import 'types.dart';

/// Returns every feed, ordered by title.
Future<List<Feed>> listFeeds() => RustLib.instance.api.crateApiFeedListFeeds();

/// Returns a single feed by id, or `NotFound` if missing.
Future<Feed> getFeed({required String feedId}) =>
    RustLib.instance.api.crateApiFeedGetFeed(feedId: feedId);

/// Inserts or updates a feed by id.
Future<void> upsertFeed({required Feed feed}) =>
    RustLib.instance.api.crateApiFeedUpsertFeed(feed: feed);

/// Updates a feed's editable metadata (title, site_url, description).
/// `NotFound` if the feed does not exist.
Future<Feed> updateFeed({
  required String feedId,
  required String title,
  required String siteUrl,
  required String description,
}) => RustLib.instance.api.crateApiFeedUpdateFeed(
  feedId: feedId,
  title: title,
  siteUrl: siteUrl,
  description: description,
);

/// Deletes a feed (and, via FK cascade, its entries). `NotFound` if missing.
Future<void> deleteFeed({required String feedId}) =>
    RustLib.instance.api.crateApiFeedDeleteFeed(feedId: feedId);

/// Sets a feed's article view mode.
Future<void> setFeedViewMode({
  required String feedId,
  required ArticleViewMode viewMode,
}) => RustLib.instance.api.crateApiFeedSetFeedViewMode(
  feedId: feedId,
  viewMode: viewMode,
);

/// Discovers feed URLs at a page. If `url` already serves a feed, returns it
/// as a single candidate; otherwise scans the HTML for
/// `<link rel="alternate" type="application/rss+xml|atom+xml">`.
Future<List<FeedCandidate>> discoverFeeds({required String url}) =>
    RustLib.instance.api.crateApiFeedDiscoverFeeds(url: url);

/// Subscribes to a feed by URL: fetch + parse + normalize + persist (metadata
/// only — entry sync is P1b). Returns the persisted `Feed`. Idempotent: an
/// existing subscription with the same source URL returns its record.
Future<Feed> subscribeFeed({required String url}) =>
    RustLib.instance.api.crateApiFeedSubscribeFeed(url: url);

/// Syncs the given feeds: fetch + parse + idempotent upsert + simhash near-dup
/// dedup per feed, emitting a `SyncProgress` event per feed plus a final
/// summary event. Per-feed failures are isolated (recorded on the feed row and
/// reported in the event's `error` field) and never abort the whole run.
Stream<SyncProgress> syncFeeds({required List<String> feedIds}) =>
    RustLib.instance.api.crateApiFeedSyncFeeds(feedIds: feedIds);

/// Syncs every subscribed feed. Convenience wrapper around [`sync_feeds`] that
/// loads all feed ids from the database first.
Stream<SyncProgress> refreshAllFeeds() =>
    RustLib.instance.api.crateApiFeedRefreshAllFeeds();

/// Refreshes a single feed (no progress stream). Returns the per-feed tally as
/// a `SyncReport`. Unlike the streaming variants, a network/parse failure here
/// surfaces as `Err` (there is only one feed, so isolation does not apply).
Future<SyncReport> refreshFeed({required String feedId}) =>
    RustLib.instance.api.crateApiFeedRefreshFeed(feedId: feedId);
