// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Returns every feed, ordered by title.
Future<List<Feed>> listFeeds() => RustLib.instance.api.crateApiFeedListFeeds();

/// Returns a single feed by id, or `NotFound` if missing.
Future<Feed> getFeed({required String feedId}) =>
    RustLib.instance.api.crateApiFeedGetFeed(feedId: feedId);

/// Inserts or updates a feed by id.
Future<void> upsertFeed({required Feed feed}) =>
    RustLib.instance.api.crateApiFeedUpsertFeed(feed: feed);

/// Updates a feed's editable metadata (title, site_url, description).
/// `NotFound` if the feed does not exist.
Future<Feed> updateFeed({
  required String feedId,
  required String title,
  String? siteUrl,
  String? description,
}) => RustLib.instance.api.crateApiFeedUpdateFeed(
  feedId: feedId,
  title: title,
  siteUrl: siteUrl,
  description: description,
);

/// Deletes a feed (and, via FK cascade, its entries). `NotFound` if missing.
Future<void> deleteFeed({required String feedId}) =>
    RustLib.instance.api.crateApiFeedDeleteFeed(feedId: feedId);

/// Sets a feed's article view mode.
Future<void> setFeedViewMode({
  required String feedId,
  required ArticleViewMode viewMode,
}) => RustLib.instance.api.crateApiFeedSetFeedViewMode(
  feedId: feedId,
  viewMode: viewMode,
);

/// Discovers feed URLs at a page. If `url` already serves a feed, returns it
/// as a single candidate; otherwise scans the HTML for
/// `<link rel="alternate" type="application/rss+xml|atom+xml">`.
Future<List<FeedCandidate>> discoverFeeds({required String url}) =>
    RustLib.instance.api.crateApiFeedDiscoverFeeds(url: url);

/// Subscribes to a feed by URL: fetch + parse + normalize + persist (metadata
/// only — entry sync is P1b). Returns the persisted `Feed`. Idempotent: an
/// existing subscription with the same source URL returns its record.
Future<Feed> subscribeFeed({required String url}) =>
    RustLib.instance.api.crateApiFeedSubscribeFeed(url: url);

/// Subscribes to a "special" source (YouTube channel, RSSHub route, ...) by
/// resolving the user's `input` to a concrete RSS URL via the named provider,
/// then reusing the standard [`subscribe_feed`] pipeline (fetch + parse +
/// persist). The resulting feed row records `feed_type` + `provider_input` so
/// the UI can label the source and the URL can be regenerated if the RSSHub
/// base changes later.
///
/// Provider ids: `youtube` (input = a `UC...` channel id) and `rsshub`
/// (input = a route like `bilibili/user/dynamic/2267573`). Unknown providers
/// return [`AppError::InvalidInput`].
///
/// Idempotent on the generated URL (delegates to [`subscribe_feed`], which is
/// idempotent on `source_url`).
Future<Feed> subscribeSpecial({
  required String providerId,
  required String input,
}) => RustLib.instance.api.crateApiFeedSubscribeSpecial(
  providerId: providerId,
  input: input,
);

/// Syncs the given feeds: fetch + parse + idempotent upsert + simhash near-dup
/// dedup per feed, emitting a `SyncProgress` event per feed plus a final
/// summary event. Per-feed failures are isolated (recorded on the feed row and
/// reported in the event's `error` field) and never abort the whole run.
Stream<SyncProgress> syncFeeds({required List<String> feedIds}) =>
    RustLib.instance.api.crateApiFeedSyncFeeds(feedIds: feedIds);

/// Syncs every subscribed feed. Convenience wrapper around [`sync_feeds`] that
/// loads all feed ids from the database first.
Stream<SyncProgress> refreshAllFeeds() =>
    RustLib.instance.api.crateApiFeedRefreshAllFeeds();

/// Refreshes a single feed (no progress stream). Returns the per-feed tally as
/// a `SyncReport`. Unlike the streaming variants, a network/parse failure here
/// surfaces as `Err` (there is only one feed, so isolation does not apply).
Future<SyncReport> refreshFeed({required String feedId}) =>
    RustLib.instance.api.crateApiFeedRefreshFeed(feedId: feedId);
