// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `apply_folder`, `build_opml_from_feeds`, `collect_opml_feeds`, `collect_outlines`, `feed_to_outline`, `non_empty`, `parse_opml`, `rfc822_now`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OpmlFeedEntry`

/// Imports an OPML 2.0 document: parses each `<outline xmlUrl=...>`, subscribes
/// to the feed (fetch + parse + persist), and applies folder/category nesting.
///
/// Per-feed failures are isolated and reported in [`ImportReport::failed_urls`].
/// Already-subscribed feeds (matched by `source_url`) are skipped without a
/// network round-trip - only their folder/category is updated.
///
/// This is an `async fn` because each new subscription performs an HTTP fetch
/// via [`feed::subscribe_feed_impl`]. FRB v2.12 hosts a tokio runtime, so the
/// awaits work directly (see `directory-structure.md` gotcha).
Future<ImportReport> importOpml({required String xml}) =>
    RustLib.instance.api.crateApiOpmlImportOpml(xml: xml);

/// Exports the current feed list to an OPML 2.0 XML string. Feeds are grouped
/// by `folder` into nested `<outline>` elements.
///
/// This is a plain `pub fn` (runs on the FRB worker pool): it only reads the
/// database and serializes XML, with no network I/O.
Future<String> exportOpml() => RustLib.instance.api.crateApiOpmlExportOpml();
