// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns the raw value stored under `key`, or `None` if unset.
///
/// Prefer the typed getters (e.g. [`get_rsshub_base_url`]) when they exist —
/// they apply defaults and value normalization. This raw variant exists for
/// keys that don't have a typed accessor yet (P4/P6 config knobs).
Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiSettingsGetSetting(key: key);

/// Inserts or updates the value for `key`. Passing `None` stores SQL `NULL`
/// (an "explicitly cleared" setting); passing `Some("")` is treated the same
/// by the typed getters, which fall back to their default.
Future<void> setSetting({required String key, String? value}) =>
    RustLib.instance.api.crateApiSettingsSetSetting(key: key, value: value);

/// Returns the configured RSSHub base URL, or the built-in default
/// (`https://rsshub.app`) when nothing is stored. The returned URL has no
/// trailing slash (matching what the RSSHub provider consumes when building
/// per-subscription URLs).
///
/// This mirrors Livo's `settings.general.rsshubInstance ||
/// DEFAULT_RSSHUB_INSTANCE` fallback in `feed-source-provider.ts`.
Future<String> getRsshubBaseUrl() =>
    RustLib.instance.api.crateApiSettingsGetRsshubBaseUrl();

/// Persists the RSSHub base URL. Passing `None` or an all-whitespace/empty
/// string clears the override; subsequent reads fall back to the default.
///
/// The stored value is trimmed but otherwise unvalidated — callers already
/// know the URL is well-formed (the settings dialog validates), and the fetch
/// layer produces a clear network error at subscribe time otherwise.
Future<void> setRsshubBaseUrl({String? url}) =>
    RustLib.instance.api.crateApiSettingsSetRsshubBaseUrl(url: url);

/// The compile-time default RSSHub base URL. Exposed so the Flutter settings
/// dialog can render it as a placeholder / reset target without hard-coding
/// the same string on both sides of the bridge.
Future<String> defaultRsshubBaseUrl() =>
    RustLib.instance.api.crateApiSettingsDefaultRsshubBaseUrl();
