// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Previous/next entry ids within a filter context, used for prev/next
/// navigation in the reading UI. The list is ordered by `published_at DESC`
/// (newest-first), so `prev` is the newer neighbour and `next` is the older
/// neighbour. Either may be `None` at the ends of the list.
class AdjacentEntries {
  final String? prev;
  final String? next;

  const AdjacentEntries({this.prev, this.next});

  @override
  int get hashCode => prev.hashCode ^ next.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdjacentEntries &&
          runtimeType == other.runtimeType &&
          prev == other.prev &&
          next == other.next;
}

/// How a feed's articles should be displayed.
///
/// `External` is escaped to `external_` in generated Dart because `external`
/// is a Dart reserved word.
enum ArticleViewMode {
  global,
  webpage,
  rendered,
  external_;

  static Future<ArticleViewMode> default_() =>
      RustLib.instance.api.crateApiTypesArticleViewModeDefault();
}

/// A simple category/folder grouping.
class Category {
  final String id;
  final String title;

  const Category({required this.id, required this.title});

  @override
  int get hashCode => id.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title;
}

/// A single article/entry belonging to a feed.
class Entry {
  final String id;
  final String feedId;
  final String title;
  final String url;
  final String? content;
  final String? summary;
  final String? author;
  final String? imageUrl;
  final DateTime publishedAt;
  final bool isRead;
  final bool isStarred;
  final double? readProgress;
  final DateTime createdAt;

  const Entry({
    required this.id,
    required this.feedId,
    required this.title,
    required this.url,
    this.content,
    this.summary,
    this.author,
    this.imageUrl,
    required this.publishedAt,
    required this.isRead,
    required this.isStarred,
    this.readProgress,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      feedId.hashCode ^
      title.hashCode ^
      url.hashCode ^
      content.hashCode ^
      summary.hashCode ^
      author.hashCode ^
      imageUrl.hashCode ^
      publishedAt.hashCode ^
      isRead.hashCode ^
      isStarred.hashCode ^
      readProgress.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Entry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          feedId == other.feedId &&
          title == other.title &&
          url == other.url &&
          content == other.content &&
          summary == other.summary &&
          author == other.author &&
          imageUrl == other.imageUrl &&
          publishedAt == other.publishedAt &&
          isRead == other.isRead &&
          isStarred == other.isStarred &&
          readProgress == other.readProgress &&
          createdAt == other.createdAt;
}

/// Input for creating an entry (used during feed import).
class EntryDraft {
  final String title;
  final String url;
  final String? author;
  final String? summary;
  final String? content;
  final DateTime? publishedAt;

  const EntryDraft({
    required this.title,
    required this.url,
    this.author,
    this.summary,
    this.content,
    this.publishedAt,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      url.hashCode ^
      author.hashCode ^
      summary.hashCode ^
      content.hashCode ^
      publishedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDraft &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          url == other.url &&
          author == other.author &&
          summary == other.summary &&
          content == other.content &&
          publishedAt == other.publishedAt;
}

/// Lightweight entry used in list views.
class EntryListItem {
  final String id;
  final String feedId;
  final String feedTitle;
  final String title;
  final String summary;
  final DateTime? publishedAt;
  final bool isRead;
  final bool isStarred;

  const EntryListItem({
    required this.id,
    required this.feedId,
    required this.feedTitle,
    required this.title,
    required this.summary,
    this.publishedAt,
    required this.isRead,
    required this.isStarred,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      feedId.hashCode ^
      feedTitle.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      publishedAt.hashCode ^
      isRead.hashCode ^
      isStarred.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryListItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          feedId == other.feedId &&
          feedTitle == other.feedTitle &&
          title == other.title &&
          summary == other.summary &&
          publishedAt == other.publishedAt &&
          isRead == other.isRead &&
          isStarred == other.isStarred;
}

/// A subscribed feed.
///
/// Ported from Livo `src/shared/types/feed.ts`. Uses `DateTime<Utc>` for
/// timestamps; `site_url`/`description` are nullable to match the schema.
class Feed {
  final String id;
  final String title;

  /// RSS/Atom source URL.
  final String sourceUrl;

  /// Human-facing website URL (may differ from the feed URL).
  final String? siteUrl;
  final String? description;
  final String? imageUrl;
  final String? folder;
  final String? category;
  final ArticleViewMode articleViewMode;
  final int unreadCount;
  final int articleCount;
  final DateTime? lastSyncedAt;
  final String? lastError;
  final int errorCount;

  /// HTTP caching helpers.
  final String? etag;
  final String? lastModified;
  final DateTime createdAt;

  const Feed({
    required this.id,
    required this.title,
    required this.sourceUrl,
    this.siteUrl,
    this.description,
    this.imageUrl,
    this.folder,
    this.category,
    required this.articleViewMode,
    required this.unreadCount,
    required this.articleCount,
    this.lastSyncedAt,
    this.lastError,
    required this.errorCount,
    this.etag,
    this.lastModified,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      sourceUrl.hashCode ^
      siteUrl.hashCode ^
      description.hashCode ^
      imageUrl.hashCode ^
      folder.hashCode ^
      category.hashCode ^
      articleViewMode.hashCode ^
      unreadCount.hashCode ^
      articleCount.hashCode ^
      lastSyncedAt.hashCode ^
      lastError.hashCode ^
      errorCount.hashCode ^
      etag.hashCode ^
      lastModified.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Feed &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          sourceUrl == other.sourceUrl &&
          siteUrl == other.siteUrl &&
          description == other.description &&
          imageUrl == other.imageUrl &&
          folder == other.folder &&
          category == other.category &&
          articleViewMode == other.articleViewMode &&
          unreadCount == other.unreadCount &&
          articleCount == other.articleCount &&
          lastSyncedAt == other.lastSyncedAt &&
          lastError == other.lastError &&
          errorCount == other.errorCount &&
          etag == other.etag &&
          lastModified == other.lastModified &&
          createdAt == other.createdAt;
}

/// A feed URL discovered via auto-discovery (`<link rel="alternate">`), or the
/// input URL itself when it already serves a feed. Returned by
/// `api::feed::discover_feeds` so the Flutter add-feed dialog can let the user
/// pick among multiple candidates before subscribing.
class FeedCandidate {
  /// Absolute feed URL.
  final String url;

  /// Optional human-readable title from the `<link title>` attribute.
  final String? title;

  /// MIME type hint (`application/rss+xml`, `application/atom+xml`, ...).
  final String? mimeType;

  const FeedCandidate({required this.url, this.title, this.mimeType});

  @override
  int get hashCode => url.hashCode ^ title.hashCode ^ mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedCandidate &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          mimeType == other.mimeType;
}

/// Input for subscribing to a new feed (pre-fetch).
class FeedDraft {
  final String title;
  final String sourceUrl;
  final String? siteUrl;
  final String? description;

  const FeedDraft({
    required this.title,
    required this.sourceUrl,
    this.siteUrl,
    this.description,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      sourceUrl.hashCode ^
      siteUrl.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedDraft &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          sourceUrl == other.sourceUrl &&
          siteUrl == other.siteUrl &&
          description == other.description;
}

/// Tally of an OPML import run. Returned by `api::opml::import_opml`.
///
/// `imported` counts newly subscribed feeds; `skipped` counts feeds that were
/// already subscribed (idempotent on `source_url`); `failed` counts feeds whose
/// subscription failed (network/parse error). `failed_urls` lists every URL
/// that could not be subscribed.
class ImportReport {
  final int total;
  final int imported;
  final int failed;
  final int skipped;
  final List<String> failedUrls;

  const ImportReport({
    required this.total,
    required this.imported,
    required this.failed,
    required this.skipped,
    required this.failedUrls,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      imported.hashCode ^
      failed.hashCode ^
      skipped.hashCode ^
      failedUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportReport &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          imported == other.imported &&
          failed == other.failed &&
          skipped == other.skipped &&
          failedUrls == other.failedUrls;
}

/// Progress payload pushed via `StreamSink` during a feed refresh.
///
/// Mirrors Livo's `FeedRefreshProgressPayload`
/// (`src/shared/renderer-events.ts`). One event is emitted per feed after it
/// has been fetched + upserted (success or failure), followed by a final
/// summary event with `done = true` and `feed_id = None`.
///
/// **FRB constraint**: a function with a `StreamSink<T>` parameter can only
/// return `()` or `Result<(), E>` - the return value is not delivered to Dart
/// as a value (only errors surface, as a stream/Future error). The cumulative
/// sync totals therefore ride on the final `SyncProgress` event (`done = true`)
/// rather than a separate `SyncReport` return value. `refresh_feed` (no stream)
/// does return a `SyncReport` directly.
class SyncProgress {
  /// Total feeds in this sync run.
  final int total;

  /// Feeds processed so far (success + failure).
  final int completed;

  /// Feeds that failed so far.
  final int failed;

  /// The feed just processed (`None` on the final summary event).
  final String? feedId;

  /// Human-readable title of the feed just processed (`None` on the summary).
  final String? feedTitle;

  /// New entries inserted for THIS feed (0 on the summary event).
  final int newEntries;

  /// Cumulative new entries across all feeds so far.
  final int totalNewEntries;

  /// `true` on the final summary event.
  final bool done;

  /// Per-feed error message when this feed failed (`None` on success/summary).
  final String? error;

  const SyncProgress({
    required this.total,
    required this.completed,
    required this.failed,
    this.feedId,
    this.feedTitle,
    required this.newEntries,
    required this.totalNewEntries,
    required this.done,
    this.error,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      completed.hashCode ^
      failed.hashCode ^
      feedId.hashCode ^
      feedTitle.hashCode ^
      newEntries.hashCode ^
      totalNewEntries.hashCode ^
      done.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncProgress &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          completed == other.completed &&
          failed == other.failed &&
          feedId == other.feedId &&
          feedTitle == other.feedTitle &&
          newEntries == other.newEntries &&
          totalNewEntries == other.totalNewEntries &&
          done == other.done &&
          error == other.error;
}

/// Final tally of a sync run. Returned directly by the non-streaming
/// `refresh_feed`; for the streaming `sync_feeds`/`refresh_all_feeds` the same
/// data is carried by the final `SyncProgress` event (see its docs for why).
class SyncReport {
  final int total;
  final int completed;
  final int failed;
  final int newEntries;

  const SyncReport({
    required this.total,
    required this.completed,
    required this.failed,
    required this.newEntries,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      completed.hashCode ^
      failed.hashCode ^
      newEntries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncReport &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          completed == other.completed &&
          failed == other.failed &&
          newEntries == other.newEntries;
}
