// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// A simple category/folder grouping.
class Category {
  final String id;
  final String title;

  const Category({required this.id, required this.title});

  @override
  int get hashCode => id.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title;
}

/// A single article/entry belonging to a feed.
///
/// Ported from Livo `src/shared/types/entry.ts`, simplified to the fields
/// needed for the P0b persistence layer. Readability/AI/media fields will be
/// added in later tasks.
class Entry {
  final String id;
  final String feedId;
  final String title;
  final String url;
  final String? content;
  final String? summary;
  final String? author;
  final String? imageUrl;
  final DateTime publishedAt;
  final bool isRead;
  final bool isStarred;
  final double? readProgress;
  final DateTime createdAt;

  const Entry({
    required this.id,
    required this.feedId,
    required this.title,
    required this.url,
    this.content,
    this.summary,
    this.author,
    this.imageUrl,
    required this.publishedAt,
    required this.isRead,
    required this.isStarred,
    this.readProgress,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      feedId.hashCode ^
      title.hashCode ^
      url.hashCode ^
      content.hashCode ^
      summary.hashCode ^
      author.hashCode ^
      imageUrl.hashCode ^
      publishedAt.hashCode ^
      isRead.hashCode ^
      isStarred.hashCode ^
      readProgress.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Entry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          feedId == other.feedId &&
          title == other.title &&
          url == other.url &&
          content == other.content &&
          summary == other.summary &&
          author == other.author &&
          imageUrl == other.imageUrl &&
          publishedAt == other.publishedAt &&
          isRead == other.isRead &&
          isStarred == other.isStarred &&
          readProgress == other.readProgress &&
          createdAt == other.createdAt;
}

/// Input for creating an entry (used during feed import).
class EntryDraft {
  final String title;
  final String url;
  final String? author;
  final String? summary;
  final String? content;
  final DateTime? publishedAt;

  const EntryDraft({
    required this.title,
    required this.url,
    this.author,
    this.summary,
    this.content,
    this.publishedAt,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      url.hashCode ^
      author.hashCode ^
      summary.hashCode ^
      content.hashCode ^
      publishedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDraft &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          url == other.url &&
          author == other.author &&
          summary == other.summary &&
          content == other.content &&
          publishedAt == other.publishedAt;
}

/// Lightweight entry used in list views.
class EntryListItem {
  final String id;
  final String feedId;
  final String feedTitle;
  final String title;
  final String summary;
  final DateTime? publishedAt;
  final bool isRead;
  final bool isStarred;

  const EntryListItem({
    required this.id,
    required this.feedId,
    required this.feedTitle,
    required this.title,
    required this.summary,
    this.publishedAt,
    required this.isRead,
    required this.isStarred,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      feedId.hashCode ^
      feedTitle.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      publishedAt.hashCode ^
      isRead.hashCode ^
      isStarred.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryListItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          feedId == other.feedId &&
          feedTitle == other.feedTitle &&
          title == other.title &&
          summary == other.summary &&
          publishedAt == other.publishedAt &&
          isRead == other.isRead &&
          isStarred == other.isStarred;
}

/// A feed URL discovered via auto-discovery (`<link rel="alternate">`), or the
/// input URL itself when it already serves a feed. Returned by
/// `api::feed::discover_feeds` so the Flutter add-feed dialog can let the user
/// pick among multiple candidates before subscribing.
class FeedCandidate {
  /// Absolute feed URL.
  final String url;

  /// Optional human-readable title from the `<link title>` attribute.
  final String? title;

  /// MIME type hint (`application/rss+xml`, `application/atom+xml`, ...).
  final String? mimeType;

  const FeedCandidate({required this.url, this.title, this.mimeType});

  @override
  int get hashCode => url.hashCode ^ title.hashCode ^ mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedCandidate &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          mimeType == other.mimeType;
}

/// Progress payload pushed via `StreamSink` during a feed refresh.
///
/// Mirrors Livo's `FeedRefreshProgressPayload`
/// (`src/shared/renderer-events.ts`).
class SyncProgress {
  final int total;
  final int completed;
  final String? feedId;
  final int newEntries;
  final bool done;

  const SyncProgress({
    required this.total,
    required this.completed,
    this.feedId,
    required this.newEntries,
    required this.done,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      completed.hashCode ^
      feedId.hashCode ^
      newEntries.hashCode ^
      done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncProgress &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          completed == other.completed &&
          feedId == other.feedId &&
          newEntries == other.newEntries &&
          done == other.done;
}
